apiVersion: apps/v1
kind: Deployment
metadata:
  #annotations:
    #kubernetes.io/change-cause: version2.0 is available
  name: schoolapp-deploy
spec:
  replicas: 7
  selector:
    matchLabels:
      app: school-app-v1
  template:
    metadata:
       name: school-pod
       labels:
         app: school-app-v1
    spec:
      containers:
      -  name: schoolapp-container
         image: mangeshabnave/cgi-app-v2
---

apiVersion: v1
kind: Service
metadata:
   name: school-app-svc
spec:
 selector:
   app: school-app-v1
 type: NodePort
 ports:
 - nodePort: 31000
   port: 80
   targetPort: 80
