apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolapp-deploy-v2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: school-app-v1
  template:
    metadata:
       name: school-pod
       labels:
         app: school-app-v1
    spec:
      containers:
      -  name: schoolapp-container
         image: mangeshabnave/cgi-app-v3
